[[inputs.mongodb]]
  ## An array of URLs of the form:
  ##   "mongodb://" [user ":" pass "@"] host [ ":" port]
  ## For example:
  ##   mongodb://user:auth_key@10.10.3.30:27017,
  ##   mongodb://10.10.3.33:18832,
  servers = ["mongodb://172.17.0.2:27017"]

  gather_perdb_stats = true

  ## When true, collect per collection stats
  #gather_col_stats = true
  #col_stats_dbs = []

[[outputs.sematext]]
  receiver_url = "https://spm-receiver.sematext.com"
  token = "6ef25fd5-7067-407d-bf82-ee47ecf41bb0"
  metric_batch_size = 200
