[[outputs.sematext]]
  receiver_url = "https://spm-receiver.sematext.com"
  token = "6a279ac2-fc27-4bc5-aab2-56a1ce5d5301"
  metric_batch_size = 200

[[inputs.apache]]
  ## An array of URLs to gather from, must be directed at the machine
  ## readable version of the mod_status page including the auto query string.
  ## Default is "http://localhost/server-status?auto".
  urls = ["http://localhost/server-status?auto"]

[[inputs.phpfpm]]
  urls = ["fcgi://172.17.0.3:9000/status"]
